Обработка ошибок в Go сводится к возврату значения типа **error** в качестве последнего возвращаемого значения функции. Когда функция выполняется ожидаемым образом, в качестве параметра ошибки возвращается значение nil. Если что-то идет не так, вместо этого возвращается значение ошибки. После этого вызывающая функция проверяет возвращаемое значение ошибки, сравнивая его со значением nil, и об­рабатывает ошибку или возвращает некоторую собственную ошибку. Сообщения об ошибке не должны начинаться с большой буквы и заканчиваться знаком пунктуации или символом новой строки. В большинстве случаев при воз­врате ненулевой ошибки остальным возвращаемым значениям следует присвоить соответствующие нулевые значения.

Тип error — это встроенный интерфейс:
``` go
type error interface {
  Error() string
}
```
Любой тип, который реализует этот интерфейс, считается ошибкой. Мы возвра­ щаем значение nil из функции при отсутствии ошибок, потому что значение nil является нулевым значением для интерфейсного типа.

В Go есть тн **сигнальные ошибки**  они сигнализируют о том, что обработка не может продолжаться из-за проблемы с текущим состоянием и обьявляются на уровне пакета. В соответствии с общепринятым
соглашением их имена начинаются на **Err**.  Таике ошибки должны обрабатываться как данные, доступные только для чтения:
``` go
if err == zip.ErrFormat {...}
```

Oшибка, созданная с помощью функции **errors.New**, равна только самой себе или переменным, которым будет явно присвоено ее значение.

Ошибки являются значениями. Поскольку тип **error** представляет собой интерфейс, вы можете определить собственные ошибки с дополнительной информацией для целей журналиро­вания или обработки ошибок. Например, иногда в ошибку требуется включить
код состояния, чтобы указать, какое сообщение выдать пользователю. Это по­зволяет вам при определении причин ошибки обойтись без сравнения строк, содержимое которых может измениться.
``` go
type Status int

const (
  InvalidLogin Status = iota + 1
  NotFound
)

type StatusErr struct {
  Status Status
  Message string
}

func (se StatusErr) Error() string {
  return se.Message
}

func Using() (error) {
  return StatusErr{
    Status: InvalidLogin,
    Message: fmt.Sprintf("invalid credentials for user %s", uid),
  }
}

```
Теперь структуру StatusErr можно использовать для предоставления более подробных сведений о том, что пошло не так.

Всегда стоит возвращать тип **error** в качестве типа возвращаемой ошибки (а не свой, но в других случаях стоит возвращать конкретный тип). Это позволит
возвращать из функции разные типы ошибок, а вызывающая сторона при этом не будет зависеть от конкретного типа ошибок.

При использовании собственного типа ошибки следует позаботиться о том, чтобы функция никогда не возвращала неинициализированный экземпляр.

Применяя пользовательские ошибки, никогда не определяйте переменную с типом вашей пользовательской ошибки. Либо явно возвращайте значе­ние **nil** при отсутствии ошибок, либо определите переменную типа **error** (вот так **var customErr error**).

Для доступа к полям и методам пользовательской ошибки не следует применять **утверждения типа** и **переключатели типа**. Вместо этого задействуйте функцию **errors.As** (о ней ниже..).

Когда ошибка передается в коде в обратном направлении, часто в нее требуется внести дополнительный контекст. Этим контекстом может быть имя функции, в которой произошла ошибка, или сведения о том, какую операцию она пыталась при этом выполнить. Если при добавлении информации исходная ошибка со­храняется, это называют **обертыванием ошибки**. Последовательность обернутых ошибок называется **цепочкой ошибок**. В стандартной библиотеке языка Go есть функция, позволяющая обертывать
ошибки. Функция **fmt.Errorf** поддерживает специ­альный глагол **%w** для создания уточненного сообщения об ошибке, содержащего исходную ошибку. Согласно общепринятому соглашению в конце форматирован­ной строки ошибки следует записать **%w**, чтобы обернуть ошибку, переданную функции **fmt.Errorf** в последнем параметре.
Стандартная библиотека также предоставляет функцию для извлечения обер­нутых ошибок — это функция **Unwrap** из пакета **errors**. Она принимает ошибку и возвращает обернутую ошибку, если такая существует. При отсутствии обер­нутой ошибки она возвращает **nil**:
``` go
func fileChecker(name string) error {
  f, err := os.Open(name)
  if err != nil {
    return fmt.Errorf("in fileChecker: %w", err)
  }
  f.Close()
  return nil
}

func main() {
  err := fileChecker("not_here.txt")
  if err != nil {
    fmt.Println(err)
    if wrappedErr := errors.Unwrap(err); wrappedErr != nil {
      fmt.Println(wrappedErr)
    }
  }
}

// output:
// in fileChecker: open not_here.txt: no such file or directory
// open not_here.txt: no such file or directory
```
Функция **errors.Unwrap** обычно не вызывается напрямую. Для поиска кон­кретной обернутой ошибки лучше воспользоваться функциями **errors.Is** и **errors.As** (о них позже..).

Если вы хотите обернуть ошибку в свой пользовательский тип, ваш тип ошибки должен реализовывать метод **Unwrap**. Он не принимает параметров и возвращает значение типа **error**:
``` go
type StatusErr struct {
	Status  Status
	Message string
	Err     error
}

func (se StatusErr) Error() string {
	return se.Message
}

func (se StatusErr) Unwrap() error {
	return se.Err
}

// Теперь мы можем использовать структуру StatusErr для обертывания базовых ошибок

func Using() error{
	err := errors.New("basic error")
	return StatusErr{
		Status: InvalidLogin,
		Message: fmt.Sprintf("invalid credentials for user %s", "John"),
		Err: err,
	}
}
```

Если вы хотите создать новую ошибку, которая содержала бы сообщение из другой ошибки, не обертывая ее при этом, создайте ошибку с помощью функции **fmt.Errorf**, используя глагол **%v** вместо **%w**:
``` go
err := internalFunction()
if err != nil {
	return fmt.Errorf("internal failure: %v", err)
}
```

Для того, чтобы вернуть несколько ошибок в типе **error** (например при валидации полей пользователя) можно воспользоваться errors.Join(errs...):
``` go
func Using(p Person) error {
	var errs []error
	if len(p.FirstName) == 0 {
		errs = append(errs, errors.New("field FirstName cannot be empty"))
	}
	if len(p.LastName) == 0 {
		errs = append(errs, errors.New("field LastName cannot be empty"))
	}
	if p.Age < 0 {
		errs = append(errs, errors.New("field Age cannot be negative"))
	}
	if len(errs) > 0 {
		return errors.Join(errs...)
	}
	return nil
}
```

Другой способ объединить несколько ошибок — передать несколько глаголов **%w** в **fmt.Errorf**:
``` go
err1 := errors.New("first error")
err2 := errors.New("second error")
err3 := errors.New("third error")
err := fmt.Errorf("first: %w, second: %w, third: %w", err1, err2, err3)
```

Или же можно реализовать свой тип **error**, поддерживающий обертывание нескольких ошибок. Для этого достаточно реализовать метод **Unwrap**, возвраща­ющий **[]error** вместо **error**:
``` go
type MyError struct {
	Code   int
	Errors []error
}

func (m MyError) Error() string {
	return errors.Join(m.Errors...).Error()
}
func (m MyError) Unwrap() []error {
	return m.Errors
}
```

